Flower.create(name: 'Alstroemeria', color: '', bunch:10, price:10.95)
Flower.create(name: 'Amaranthus ', color: '', bunch:10, price:14.95)
Flower.create(name: 'Anemone', color: '', bunch:10, price:0)
Flower.create(name: 'Asiatic/L.A. Hybrid Lily', color: '', bunch:10, price:19.95)
Flower.create(name: 'Bells of Ireland', color: '', bunch:10, price:15.95)
Flower.create(name: 'Broom Corn', color: '', bunch:10, price:11.95)
Flower.create(name: 'Bupleurum', color: '', bunch:10, price:12.95)
Flower.create(name: 'Calla Lily - Mini White', color: 'White', bunch:10, price:24.95)
Flower.create(name: 'Calla Lily - Mini Colors/Tall', color: '', bunch:10, price:31.95)
Flower.create(name: 'Calla Lily - Open Cut', color: '', bunch:1, price:4.45)
Flower.create(name: 'Carnation', color: '', bunch:25, price:14.75)
Flower.create(name: 'Carnation - Mini', color: '', bunch:10, price:6.45)
Flower.create(name: 'Carnation - Moon Series', color: '', bunch:20, price:15.8)
Flower.create(name: 'Carnation - Mini Moon Series', color: '', bunch:10, price:8.45)
Flower.create(name: 'Cornflower', color: '', bunch:10, price:12.95)
Flower.create(name: 'Cotinus', color: '', bunch:10, price:13.95)
Flower.create(name: 'Craspedia', color: '', bunch:10, price:12.95)
Flower.create(name: 'Crocosmia/Montbretia', color: '', bunch:10, price:14.95)
Flower.create(name: 'Dahlias', color: '', bunch:10, price:0)
Flower.create(name: 'Delphinium', color: '', bunch:10, price:16.95)
Flower.create(name: 'Disbud/Cremon/Fuji', color: '', bunch:10, price:11.95)
Flower.create(name: 'Eryngium', color: '', bunch:10, price:14.95)
Flower.create(name: 'Football Mum', color: '', bunch:10, price:14.95)
Flower.create(name: 'Gerbera', color: '', bunch:1, price:1.49)
Flower.create(name: 'Gerbera - Mini', color: '', bunch:1, price:1.39)
Flower.create(name: 'Gladiolus', color: '', bunch:10, price:19.95)
Flower.create(name: 'Green Trick', color: '', bunch:10, price:14.95)
Flower.create(name: 'Hydrangea - Mini Green', color: '', bunch:1, price:2.95)
Flower.create(name: 'Hydrangea - Regular', color: '', bunch:1, price:3.95)
Flower.create(name: 'Hydrangea - Select', color: '', bunch:1, price:5.95)
Flower.create(name: 'Hydrangea - Premium', color: '', bunch:1, price:7.95)
Flower.create(name: 'Iris', color: '', bunch:10, price:12.95)
Flower.create(name: 'Kale', color: '', bunch:5, price:15.95)
Flower.create(name: 'Larkspur', color: '', bunch:10, price:14.95)
Flower.create(name: 'Leucodendron - Safari Sunset/Novelty', color: '', bunch:10, price:12.95)
Flower.create(name: 'Liatris', color: '', bunch:10, price:19.95)
Flower.create(name: 'Matsumoto Aster', color: '', bunch:10, price:12.95)
Flower.create(name: 'Millet', color: '', bunch:10, price:9.95)
Flower.create(name: 'Nigella', color: '', bunch:10, price:14.95)
Flower.create(name: 'Oriental Lily (Milti-Bloom) - Pink', color: '', bunch:10, price:33.95)
Flower.create(name: 'Oriental Lily (Milti-Bloom) - White', color: '', bunch:10, price:36.95)
Flower.create(name: 'Peonies', color: '', bunch:5, price:0)
Flower.create(name: 'Pom Pom', color: '', bunch:10, price:4.95)
Flower.create(name: 'Ranunculus', color: '', bunch:10, price:0)
Flower.create(name: 'Rose Hips', color: '', bunch:10, price:19.95)
Flower.create(name: 'Safflower', color: '', bunch:10, price:13.95)
Flower.create(name: 'Scabiosa', color: '', bunch:10, price:13.95)
Flower.create(name: 'Snapdragon', color: '', bunch:10, price:14.95)
Flower.create(name: 'Stock', color: '', bunch:10, price:15.95)
Flower.create(name: 'Succulent', color: '', bunch:10, price:0)
Flower.create(name: 'Sunflower', color: '', bunch:5, price:10.95)
Flower.create(name: 'Sunflower - Mini', color: '', bunch:10, price:11.95)
Flower.create(name: 'Sweet William/Dianthus', color: '', bunch:10, price:12.95)
Flower.create(name: 'Tulip - Regular', color: '', bunch:10, price:14.95)
Flower.create(name: 'Veronica', color: '', bunch:10, price:16.95)
Flower.create(name: 'Yarrow', color: '', bunch:10, price:11.95)
Flower.create(name: 'SA Rose 40cm', color: '', bunch:25, price:30.5)
Flower.create(name: 'SA Rose 50cm', color: '', bunch:25, price:33)
Flower.create(name: 'SA Rose 60cm', color: '', bunch:25, price:35.5)
Flower.create(name: 'SA Rose 70cm', color: '', bunch:25, price:38)
Flower.create(name: 'SA Rose 80cm', color: '', bunch:25, price:39)
Flower.create(name: 'Cal. Rose - Sweetheart', color: '', bunch:25, price:34.5)
Flower.create(name: 'Cal. Rose - Regular', color: '', bunch:25, price:37)
Flower.create(name: 'Garden Roses - Regular', color: '', bunch:12, price:47.4)
Flower.create(name: 'Garden Roses - Premium', color: '', bunch:12, price:57)
Flower.create(name: 'Spray Rose - Regular', color: '', bunch:10, price:23.95)
Flower.create(name: 'Spray Rose - Select', color: '', bunch:10, price:26.95)
Flower.create(name: 'Spray Rose - Premium', color: '', bunch:10, price:29.95)
Flower.create(name: 'Anthurium', color: '', bunch:1, price:5.45)
Flower.create(name: 'Bird of Paradise', color: '', bunch:1, price:2.95)
Flower.create(name: 'Cymbidium Orchid Spray', color: '', bunch:10, price:31.95)
Flower.create(name: 'Dendrobium Orchid', color: '', bunch:10, price:32.95)
Flower.create(name: 'Ginger - Red/Pink/Assorted', color: '', bunch:1, price:4.95)
Flower.create(name: 'Protea', color: '', bunch:10, price:0)
Flower.create(name: 'Aster - Purple Premium', color: '', bunch:10, price:12.95)
Flower.create(name: 'Aster - White Premium', color: '', bunch:10, price:12.95)
Flower.create(name: 'Aster - Yellow Premium', color: '', bunch:10, price:12.95)
Flower.create(name: 'Gyp - Million Star/Xcellence', color: '', bunch:10, price:10.95)
Flower.create(name: 'Gyp - Overtime', color: '', bunch:10, price:12.95)
Flower.create(name: 'Hypericum', color: '', bunch:10, price:11.95)
Flower.create(name: 'Misty - Blue/White/Pink/Yellow', color: '', bunch:10, price:11.95)
Flower.create(name: 'Queen Annes Lace/Green Mist', color: '', bunch:10, price:12.95)
Flower.create(name: 'Statice - Tissue Culture/Seafoam', color: '', bunch:10, price:8.95)
Flower.create(name: 'Tracellium', color: '', bunch:10, price:13.95)
Flower.create(name: 'Waxflower', color: '', bunch:10, price:13.95)